### ISSUE TITLE
Upgrade frontend dependencies

### ISSUE THREAD

**Issue by garg3133** [BitByte-TPC/TPC-website#78]
## Describe the bug

Right now, on doing `npm i`, we get the following deprecation warnings:

```sh
> npm i
             
npm WARN deprecated @material-ui/styles@4.11.5: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
npm WARN deprecated @material-ui/pickers@3.3.11: This package no longer supported. It has been relaced by @mui/x-date-pickers
npm WARN deprecated @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
npm WARN deprecated @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
```

So, we should consider upgrading material-ui, as well as other dependencies to the latest version. Please refer to #73 for more details.

### TODO:

- [ ] Upgrade material-ui to v5 (which has some [breaking changes](https://mui.com/material-ui/migration/migration-v4/)).
- [ ] Upgrade `react-router-dom` to v6, which again has some [breaking changes](https://reactrouter.com/en/main/upgrading/v5).
- [ ] Upgrade React to v8, along with other dependencies as done in #73.
